[package]
name = "blinky"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7"
cortex-m    = "0.7"          # needed for SYST-based delay
stm32f3xx-hal = { version = "0.10", features = ["stm32f303xe"] }
panic-halt = "0.2"

[profile.release]
opt-level = "s"   # optimize for size
lto = true
